### ISSUE TITLE
whereami - can I fix it for Nukepedia?

### ISSUE THREAD

**Issue by frueter** [antiero/dotStudio#13]
Hi Ant,

not sure if you are still involved in any Hiero python coding.
I just stumbled across your whereami.py (luckily, cause I was about to spend my day writing exactly that).
Do you mind if I fix up the code a little and post it on Nukepedia?

Hope you are well.

Cheers,
frank

**Comment by antiero** [comment]
Hi Frank, yes of course, go for it! I haven't tested this code out for ages so can't promise that it's functional in the latest build! Cheers, Ant

**Comment by frueter** [comment]
Cool. Thanks. It's using a couple of hiero api calls that don't seem too do the right thing when testing them in isolation. In context of your script they seem to be ok,  but need to test more.
Also, do you remember a reason for excluding the active sequence from being  listed in the custom menu?
Cheers, Frank

Sent from phone booth
-------- Original message --------From: antiero <notifications@github.com> Date: 04/06/2018  7:09 pm  (GMT+12:00) To: antiero/dotStudio <dotStudio@noreply.github.com> Cc: Frank Rueter <frank@ohufx.com>, Author <author@noreply.github.com> Subject: Re: [antiero/dotStudio] whereami - can I fix it for Nukepedia? (#13) 
Hi Frank, yes of course, go for it! I haven't tested this code out for ages so can't promise that it's functional in the latest build! Cheers, Ant

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/antiero/dotStudio/issues/13#issuecomment-394255497","url":"https://github.com/antiero/dotStudio/issues/13#issuecomment-394255497","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/antiero/dotStudio","title":"antiero/dotStudio","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/antiero/dotStudio"}},"updates":{"snippets":[{"icon":"PERSON","message":"@antiero in #13: Hi Frank, yes of course, go for it! I haven't tested this code out for ages so can't promise that it's functional in the latest build! Cheers, Ant"}],"action":{"name":"View Issue","url":"https://github.com/antiero/dotStudio/issues/13#issuecomment-394255497"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [antiero/dotStudio] whereami - can I fix it for Nukepedia? (#13)",
"sections": [
{
"text": "",
"activityTitle": "**antiero**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@antiero",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"antiero/dotStudio\",\n\"issueId\": 13,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"antiero/dotStudio\",\n\"issueId\": 13\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/antiero/dotStudio/issues/13#issuecomment-394255497"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 341961138\n}"
}
],
"themeColor": "26292E"
}

**Comment by antiero** [comment]
Fixed up some behaviour to make this show the clip in the active Sequence too. Closing.
