### ISSUE TITLE
NukeStudio 12 There are many mistakes

### ISSUE THREAD

**Issue by justinli** [antiero/dotStudio#15]
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG <hiero.core.FnExportRegistry.TaskRegistry object at 0x000002CC921B4448>
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Task Registered <class 'hiero.core.FnExporterBase.TaskBase'>
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Task Registered <class 'hiero.core.FnExporterBase.FolderTask'>
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Loading Python hiero.importers package
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG Loading Python hiero.exporters package
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Task Registered <class 'hiero.exporters.FnSymLinkExporter.SymLinkExporter'>
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Task Registered <class 'hiero.exporters.FnCopyExporter.CopyExporter'>
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Task Registered <class 'hiero.exporters.FnExternalRender.ExternalRenderTask'>
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Task Registered <class 'hiero.exporters.FnExternalRender.NukeRenderTask'>
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Task Registered <class 'hiero.exporters.FnNukeShotExporter.NukeShotExporter'>
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Task Registered <class 'hiero.exporters.FnNukeShotExporter.NukeSequenceExporter'>
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Task Registered <class 'hiero.exporters.FnNukeAnnotationsExporter.NukeAnnotationsExporter'>
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Task Registered <class 'hiero.exporters.FnTranscodeExporter.TranscodeExporter'>
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG Registering EDLExportTask
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Task Registered <class 'hiero.exporters.FnEDLExportTask.EDLExportTask'>
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Task Registered <class 'hiero.exporters.FnXMLExportTask.XMLExportTask'>
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Task Registered <class 'hiero.exporters.FnAudioExportTask.AudioExportTask'>
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG Task UI Registered <class 'hiero.exporters.FnSymLinkExporter.SymLinkPreset'> <class 'hiero.exporters.FnSymLinkExporterUI.SymLinkExporterUI'>
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG Task UI Registered <class 'hiero.exporters.FnCopyExporter.CopyPreset'> <class 'hiero.exporters.FnCopyExporterUI.CopyExporterUI'>
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG Task UI Registered <class 'hiero.exporters.FnNukeShotExporter.NukeShotPreset'> <class 'hiero.exporters.FnNukeShotExporterUI.NukeShotExporterUI'>
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG Task UI Registered <class 'hiero.exporters.FnNukeShotExporter.NukeSequencePreset'> <class 'hiero.exporters.FnNukeShotExporterUI.NukeShotExporterUI'>
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG Task UI Registered <class 'hiero.exporters.FnNukeAnnotationsExporter.NukeAnnotationsPreset'> <class 'hiero.exporters.FnNukeAnnotationsExporterUI.NukeAnnotationsExporterUI'>
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG Task UI Registered <class 'hiero.exporters.FnExternalRender.ExternalRenderPreset'> <class 'hiero.exporters.FnExternalRenderUI.ExternalRenderTaskUI'>
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG Task UI Registered <class 'hiero.exporters.FnExternalRender.NukeRenderPreset'> <class 'hiero.exporters.FnExternalRenderUI.NukeRenderTaskUI'>
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG Task UI Registered <class 'hiero.exporters.FnTranscodeExporter.TranscodePreset'> <class 'hiero.exporters.FnTranscodeExporterUI.TranscodeExporterUI'>
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG Task UI Registered <class 'hiero.exporters.FnEDLExportTask.EDLExportPreset'> <class 'hiero.exporters.FnEDLExportUI.EDLExportUI'>
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG Task UI Registered <class 'hiero.exporters.FnXMLExportTask.XMLExportPreset'> <class 'hiero.exporters.FnXMLExportUI.XMLExportUI'>
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG Task UI Registered <class 'hiero.exporters.FnAudioExportTask.AudioExportPreset'> <class 'hiero.exporters.FnAudioExportUI.AudioExportUI'>
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Processor Registered <class 'hiero.exporters.FnShotProcessor.ShotProcessor'>
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG registerProcessorUI
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG Processor UI Registered <class 'hiero.exporters.FnShotProcessor.ShotProcessorPreset'> <class 'hiero.exporters.FnShotProcessorUI.ShotProcessorUI'>
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Processor Registered <class 'hiero.exporters.FnTimelineProcessor.TimelineProcessor'>
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG registerProcessorUI
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG Processor UI Registered <class 'hiero.exporters.FnTimelineProcessor.TimelineProcessorPreset'> <class 'hiero.exporters.FnTimelineProcessorUI.TimelineProcessorUI'>
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Processor Registered <class 'hiero.exporters.FnBinProcessor.BinProcessor'>
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG registerProcessorUI
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG Processor UI Registered <class 'hiero.exporters.FnBinProcessor.BinProcessorPreset'> <class 'hiero.exporters.FnBinProcessorUI.BinProcessorUI'>
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Searching for Python plugins:
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO   Looking for plugins in C:/Program Files/Nuke12.0v2/configs\Python\Startup
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO   Looking for plugins in C:/Users/lizhaohui/.nuke\Python\Startup
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module AESequenceExporterUI
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Task Registered <class 'AESequenceTask.AESequenceTask'>
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG Task UI Registered <class 'AESequenceTask.AESequencePreset'> <class 'AESequenceExporterUI.AESequenceUI'>
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module AESequenceTask
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Task Registered <class 'AESequenceTask.AESequenceTask'>
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading package C:/Users/lizhaohui/.nuke\Python\Startup\ExportExcel\__init__.py
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module FnFTPCopyExporter
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Task Registered <class 'FnFTPCopyExporter.FTPCopyExporter'>
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module FnFTPCopyExporterUI
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG Task UI Registered <class 'FnFTPCopyExporter.FTPCopyPreset'> <class 'FnFTPCopyExporterUI.FTPCopyExporterUI'>
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module ReinstateAudio
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module UIPopover
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module addCCVideoTrack
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module addCustomTags
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module addFxTags
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module buildDailiesTimeline
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module buildShotLayers
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module clipSplitter
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module clip_ui
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module drop_edits
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module effects_browser
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading package C:/Users/lizhaohui/.nuke\Python\Startup\fcpxml_reader\__init__.py
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module flatten_sequence
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module import_helpers
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module init
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module longest_shot
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module markers
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module nukestudio_extensions
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading package C:/Users/lizhaohui/.nuke\Python\Startup\pdf_export\__init__.py
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Task Registered <class 'pdf_export.FnPdfExportTask.PdfExportTask'>
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG Task UI Registered <class 'pdf_export.FnPdfExportTask.PdfExportPreset'> <class 'pdf_export.FnPdfExportTaskUI.PdfExportUI'>
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module power_edit
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module project_cleanup
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module quick_export
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module remove_gaps
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module script_only_submission
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module show_in_spreadsheet
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module tag_resolve_tokens
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading package C:/Users/lizhaohui/.nuke\Python\Startup\thumbnail_exporter\__init__.py
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Task Registered <class 'thumbnail_exporter.ThumbnailExportTask.ThumbnailExportTask'>
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG Task UI Registered <class 'thumbnail_exporter.ThumbnailExportTask.ThumbnailExportPreset'> <class 'thumbnail_exporter.ThumbnailExportUI.ThumbnailExportUI'>
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module timecode_helpers
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module version_everywhere
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module whereami
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module workspace_popover
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO   Looking for plugins in C:/Program Files/Nuke12.0v2/configs\Python\StartupUI
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO   Looking for plugins in C:/Users/lizhaohui/.nuke\Python\StartupUI
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module FreezeFrameMaker
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module GrabStill
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module MakeShotBins
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module NukeShotExporterUI_withShotBin
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Task Registered <class 'NukeShotExporter_withShotBin.NukeShotExporter_withShotBin'>
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG Task UI Registered <class 'NukeShotExporter_withShotBin.NukeShotWithShotBinPreset'> <class 'NukeShotExporterUI_withShotBin.NukeShotExporterUI_withShotBin'>
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module NukeShotExporter_withShotBin
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Task Registered <class 'NukeShotExporter_withShotBin.NukeShotExporter_withShotBin'>
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module PimpMySpreadsheet
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module Purge_Unused_Clips
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module Sort Items in Bin
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module _redlineExport_pw
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module _redlineExport_trigger_pw
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module frame_scribble
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module getShotsHelper
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module new_sequence_from_selection
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module project_helpers
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO     - Loading module setFrameRate
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Searching for startup projects:
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Looking for startup projects in: C:/Program Files/Nuke12.0v2/configs\StartupProjects\Hiero
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO  - Opening startup project: C:/Program Files/Nuke12.0v2/configs\StartupProjects\Hiero\HieroPresets.hrox
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG nukestudio.startServerIfEnabled
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG nukestudio.startServer
Wed, 06 Nov 2019 13:59:57 log.py[line:57] DEBUG add effect handler
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Looking for startup projects in: C:/Users/lizhaohui/.nuke\StartupProjects\Hiero
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO   Looking for plugins in C:/Program Files/Nuke12.0v2/configs\Python\Exporters
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO   Looking for plugins in C:/Users/lizhaohui/.nuke\Python\Exporters
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Preset 'Transcode Clips Avid DNxHD Codec MOV' cannot be deleted as it is not registered
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Preset 'Final Cut Pro 7 XML' cannot be deleted as it is not registered
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Preset 'Log10 Cineon DPX' cannot be deleted as it is not registered
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Preset 'Log10 Cineon DPX Multi-View' cannot be deleted as it is not registered
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Preset 'Transcode Clips Photo - JPEG MOV' cannot be deleted as it is not registered
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Preset 'Apple ProRes 422 MOV' cannot be deleted as it is not registered
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Preset 'Multi-View Nuke Shot (%v)' cannot be deleted as it is not registered
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Preset 'CMX 3600 EDL' cannot be deleted as it is not registered
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Preset 'Photo - JPEG MOV' cannot be deleted as it is not registered
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Preset 'Transcode Clips Apple ProRes 4444 MOV' cannot be deleted as it is not registered
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Preset 'Transcode Clips DPX' cannot be deleted as it is not registered
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Preset 'Basic Nuke Shot' cannot be deleted as it is not registered
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Preset 'Transcode Shots DPX' cannot be deleted as it is not registered
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Preset 'Avid DNxHD Codec MOV' cannot be deleted as it is not registered
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Preset 'Basic Nuke Shot With Annotations' cannot be deleted as it is not registered
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Preset 'Apple ProRes 4444 MOV' cannot be deleted as it is not registered
Wed, 06 Nov 2019 13:59:57 log.py[line:62] INFO Preset 'Transcode Clips Apple ProRes 422 MOV' cannot be deleted as it is not registered
[13:59.57] ERROR: oCIOColorSpace.in_colorspace: Nothing is named "parent"

**Comment by antiero** [comment]
@justinli - please contact Foundry support to determine what has changed with their API. This repo was made a long time ago, back in NukeStudio 9 days and I’m no longer maintaining it. If you have fixes, please feel free to make a pull request!

**Comment by antiero** [comment]
Closing as these reported errors are not related to dotStudio code.
