### ISSUE TITLE
Thumbnail Colourspace

### ISSUE THREAD

**Issue by tobyduffy** [antiero/dotStudio#2]
Any ability to alter the colourspace of the thumbnails? Or where would I find the thumbnail file conversion to jpg that happens to add this functionality in myself? Thanks.

**Comment by antiero** [comment]
Hmm, tricky one... It's possible to set the media colourspace on the items in the Bin, but not via the method to get thumbnail. I think the way to do this via an exporter would be to clone the item first, call setMediaColourspace on it, then do the export. Maybe drop a feature request to the TF to get a thumbnail method back with a certain colourspace?.. Cheers!
