### ISSUE TITLE
Thumbnail exporter not working in nuke studio 10.5v1

### ISSUE THREAD

**Issue by lindywong** [antiero/dotStudio#6]
The plugins is working fine in nuke studio 10.4, but it doesn't work anymore after updated to 10.5v1.
Will be very appreciated if you help us to update the thumbnail exporter. Thanks a lot.

**Comment by antiero** [comment]
@lindywong - thanks for raising this. I've reproduced this in 10.5v1. The exporter _does_ actually work with the defaults (and export thumbnails), but it appears that the UI for the Exporter is not appearing as expected in the export dialog. I have contacted The Foundry's support team to follow this up.
