### ISSUE TITLE
NukeStudio 11 All scripts Not work

### ISSUE THREAD

**Issue by justinli** [antiero/dotStudio#9]
NukeStudio 11 All scripts Not work

**Comment by antiero** [comment]
Thanks for raising this @justinli.
I've created a pyside2 branch with some fixes in (work in progress!)

**Comment by antiero** [comment]
Closing this as pyside2 branch is importing without errors in Nuke 11.0v1.

**Comment by justinli** [comment]
😇

李朝辉
Justin Li
phone:13581760760
mail:fusionnuke@gmail.com

2017-08-20 18:12 GMT+08:00 antiero <notifications@github.com>:

**Comment by justinli** [comment]
Clip, Splitter, for, split, sequences, v1.0
How to work under NukeStudio in window system?

李朝辉
Justin Li
phone:13581760760
mail:fusionnuke@gmail.com

2017-08-20 20:56 GMT+08:00 李朝辉 <fusionnuke@gmail.com>:
